version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: parcel
    versions:
    - 2.0.0-nightly.554
    - 2.0.0-nightly.560
    - 2.0.0-nightly.562
    - 2.0.0-nightly.566
    - 2.0.0-nightly.570
    - 2.0.0-nightly.573
    - 2.0.0-nightly.574
    - 2.0.0-nightly.577
    - 2.0.0-nightly.579
    - 2.0.0-nightly.585
    - 2.0.0-nightly.596
    - 2.0.0-nightly.597
    - 2.0.0-nightly.598
    - 2.0.0-nightly.600
    - 2.0.0-nightly.605
    - 2.0.0-nightly.606
    - 2.0.0-nightly.607
    - 2.0.0-nightly.608
    - 2.0.0-nightly.609
    - 2.0.0-nightly.610
    - 2.0.0-nightly.614
    - 2.0.0-nightly.615
    - 2.0.0-nightly.619
    - 2.0.0-nightly.620
    - 2.0.0-nightly.623
    - 2.0.0-nightly.626
    - 2.0.0-nightly.627
    - 2.0.0-nightly.628
    - 2.0.0-nightly.630
    - 2.0.0-nightly.631
    - 2.0.0-nightly.632
    - 2.0.0-nightly.634
    - 2.0.0-nightly.635
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.639
    - 2.0.0-nightly.640
    - 2.0.0-nightly.641
    - 2.0.0-nightly.643
    - 2.0.0-nightly.644
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
