sudo: false

language: node_js
node_js:
  - 12.18.0

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      name: Run Linters
      script: npm run lint
    - stage: test
      name: Run tests and upload coverage
      script:
      - npm run test:coverage
      - bash <(curl -s https://codecov.io/bash)
    - stage: publish
      name: Publish to npm
      script: skip
      deploy:
        provider: script
        script: npm run publish
        skip_cleanup: true
        on:
          tags: true

cache: npm

branches:
  only:
    - main
    - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
